version: '3'

services:
  
  mysql:
    image: mariadb
    volumes:
      - /home/vagrant/site/Mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: db_wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: 1
    restart: always
  
  wordpress:
    image: wordpress:php7.4-fpm-alpine
    volumes:
      - /home/vagrant/site/Wordpress:/var/www/html
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: 1
      WORDPRESS_DB_NAME: db_wordpress
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: 1
      WORDPRESS_TABLE_PREFIX: wp_
    links:
      - mysql:mysql
    restart: always
  
  nginx:
    image: nginx:stable
    volumes:
      - /home/vagrant/site/Nginx:/etc/nginx/conf.d
      - /home/vagrant/site/Nginx/data:/var/www/html
    ports:
      - 8080:80
    links:
      - wordpress

  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql:mysql
    ports:
      - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: 1