---

- name: Setting up VMs
  gather_facts: true
  hosts: Project

  tasks:

    - name: Create group "devops"
      ansible.builtin.group:
        name: devops
        state: present
        gid: 1400
      become: true

    - name: Add user "belhard"
      ansible.builtin.user:
        name: belhard
        group: devops
        shell: /bin/bash
        comment: "Belhard DevOps user"
        state: present
        uid: 1500
      become: true
    
    - name: Add belhard user to the sudoers
      copy:
        dest: "/etc/sudoers.d/belhard"
        content: |
          belhard ALL = NOPASSWD: ALL
          belhard ALL = (ALL) NOPASSWD:ALL
      become: yes

    - name: Add vagrant user to the sudoers
      copy:
        dest: "/etc/sudoers.d/belhard"
        content: |
          vagrant ALL = NOPASSWD: ALL
          vagrant ALL = (ALL) NOPASSWD:ALL
      become: yes

    - name: Add SSH keys 
      authorized_key:
         user: root
         state: present
         key: "{{ lookup('file', '/home/user/Project/Ansible/id_rsa.pub') }}"
      become: true
    
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
      become: true

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'wget', 'unzip', 'zip', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
      become: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
      become: true
    
    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
      become: true

    - name: Install Docker Module for Python
      pip:
        name: docker
      become: true
    
    - name: users | adding docker users (for use without sudo)
      user:
        name: "{{ item }}"
        shell: /bin/bash
        append: yes
        groups: docker
      with_items: [ 'vagrant', 'belhard' ]
      become: true